#!/usr/bin/env ruby
#^syntax detection

forge "https://forge.puppetlabs.com"

mod 'stankevich-python'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-firewall'
mod 'crayfishx-firewalld'
mod 'maestrodev-ssh_keygen'
